fw_payload.S: allow FDT payload where size is not 16-byte aligned
Resolves the follow compilation error (payload variant for SiFive FU540 with
U-Boot and embedded FDT):

    /usr/bin/ld: /build/platform/sifive/fu540/firmware/fw_payload.o(.text+0x1961): 15 bytes required for alignment to 16-byte boundary, but only 14 present
    /usr/bin/ld: can't relax section: bad value
    collect2: error: ld returned 1 exit status

Noticed while compiling 5.4-rc3+ kernel in Fedora/RISCV.

For more details see:
https://github.com/riscv/riscv-gnu-toolchain/issues/298

Signed-off-by: David Abdurachmanov <david.abdurachmanov@sifive.com>